### ISSUE TITLE
 US 03.02.01 As a user, I want the option to enable or disable geolocation tracking for event verification.

### ISSUE THREAD

**Issue by PhireFlai** [CMPUT301W24T41/TechTitans#18]
Story Points: TBD

Risk Level: TBD

Requirements: 

- [ ] Google map or other map integration
- [ ] checks the current users geolocation
- [ ] allows checking in if user is in set proximity of event location
- [ ] user can disable geolocation tracking if they wish

Acceptance Criteria: TBD
