### ISSUE TITLE
US 01.05.01 As an organizer, I want to track real-time attendance and receive alerts for important milestones.

### ISSUE THREAD

**Issue by PhireFlai** [CMPUT301W24T41/TechTitans#7]
Story Points: TBD

Risk Level: TBD

Requirements: 

- [ ] Display number of attendees
- [ ] Milestones should be customizable by organizers (ie. certain amount of attendees reached, event start time passed, or have no milestones at all)
- [ ] Milestones should send notifications to the organizer
- [ ] Organizers should have the option to silence milestone notifications

Acceptance Criteria: TBD
